#!/usr/bin/env python3
"""Generate docs/llms.txt with EVERY markdown page URL (MkDocs directory_urls).

Usage (from repo root):
  python scripts/generate_llms_txt.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "llms.txt"
BASE = "https://docs.telebothost.com"
SKIP = {"SUMMARY.md"}


def src_to_url(rel: str) -> str:
    rel = rel.replace("\\", "/")
    if rel == "index.md":
        return f"{BASE}/"
    if rel.endswith("/index.md"):
        return f"{BASE}/{rel[: -len('index.md')]}"
    if rel.endswith(".md"):
        return f"{BASE}/{rel[:-3]}/"
    return f"{BASE}/{rel}"


def section_key(rel: str) -> str:
    rel = rel.replace("\\", "/")
    if "/" not in rel:
        return "_root"
    return rel.split("/", 1)[0]


SECTION_TITLES = {
    "_root": "Site root",
    "start-here": "Start here",
    "tutorials": "Tutorials",
    "getting-started-with-tbl": "Command flow / getting started with TBL",
    "guides": "Guides",
    "globals": "Global variables",
    "bot-instance": "Bot",
    "api-instance": "Api",
    "msg-instance": "msg",
    "db-instance": "Database (db)",
    "user-instance": "User storage (deprecated)",
    "global-instance": "Global storage (removed)",
    "http-instance": "HTTP client",
    "webhook-instance": "Webhooks",
    "webapp-instance": "Webapps",
    "res-instance": "HTTP responses (res)",
    "modules": "Modules",
    "libs": "TBL Libraries (Libs)",
    "tbl-instance": "TBL instance (clone / transfer)",
}


def main() -> None:
    pages: list[str] = []
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(DOCS).as_posix()
        if rel in SKIP or path.name == "llms.txt":
            continue
        pages.append(rel)

    by_section: dict[str, list[str]] = defaultdict(list)
    for rel in pages:
        by_section[section_key(rel)].append(rel)

    # Stable section order
    order = [
        "_root",
        "start-here",
        "tutorials",
        "getting-started-with-tbl",
        "guides",
        "globals",
        "bot-instance",
        "api-instance",
        "msg-instance",
        "db-instance",
        "http-instance",
        "webhook-instance",
        "webapp-instance",
        "res-instance",
        "modules",
        "libs",
        "tbl-instance",
        "user-instance",
        "global-instance",
    ]
    for key in sorted(by_section.keys()):
        if key not in order:
            order.append(key)

    lines = [
        "# TeleBotHost / TBL — LLM docs index (COMPLETE)",
        f"# Site: {BASE}/",
        "# Generated by: python scripts/generate_llms_txt.py",
        "# Rule for agents: pick ONE URL for the task. Do not fetch every URL.",
        f"# Human map: {BASE}/for-agents/",
        "",
        "## How to use",
        "1. Scan section headings / path names for your topic.",
        "2. Fetch that single URL.",
        "3. Write TBL from that page + workspace AGENTS.md.",
        "4. Open a second page only if needed.",
        "",
        f"## All pages ({len(pages)})",
        "",
    ]

    for key in order:
        rels = by_section.get(key)
        if not rels:
            continue
        title = SECTION_TITLES.get(key, key)
        lines.append(f"## {title}")
        # section index first if present
        rels_sorted = sorted(
            rels,
            key=lambda r: (0 if r.endswith("index.md") or r.count("/") == 0 else 1, r),
        )
        for rel in rels_sorted:
            lines.append(src_to_url(rel))
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(pages)} pages)")


if __name__ == "__main__":
    main()
